- ddoc2.js
- load/dmbase.js
- load/dperuser.js
* Consolidated debug settings and all other per-user settings into a single JSON, data/users/docusers.
* All DDOC debug and user settings are now kept in the global userSettings.  The format is shown in dperuser.js:userRecords.defaultSettings();
* The settings object and methods have been written with expansion in mind, adding new user settings should be pretty easy in the future.
* The methods to load/save/etc the user settings mostly take a userid (Synchronet user.number) so that sysop menus can have commands to change other users' settings.
* There are a couple of TODO: tags left in this commit to set up as future tasks.
***Conflicts:***
***ddoc2.js***
***load/dmbase.js***
***Conflicts corrected.  Search for FIXME in ddoc2.js for a conflict fix I wasn't sure about.***
> Near total rewrite of dperuser.js.

- ddoc2.js
- load/dperuser.js
Added userid to displayDebugFlags call.
Removed accidental double-call of Object.keys in displayDebugFlags.
> Fixed some minor mistakes

- ddoc2.js
- load/dmbase.js
- load/dpoast.js
Fixed debug message
Fixed debug flag checking in dpoast
Fixed debug flag checking in dmbase
> Debugchecks

- ddoc2.js
- load/dmbase.js
- load/dperuser.js
Changed function calls and confined checks to match.
Also added a "doing" property for future use.
> Added confined to userSettings

- ddoc2.js
sub_list[x] object has no .cfg sub-object
> This should be rm.code

- ddoc2.js
- load/dmbase.js
Test forward and backwards scanning thoroughly
> scanSub() should be working.

- load/dmbase.js
So apparently I misunderstood the Synchronet JS spec, total_msgs is 0-based.
fixes #51
> Fixed last message not showing

- load/dmbase.js
- load/dperuser.js
Implemented \<a>gain and \<A>gain (no breaks).
Also figured out why doMprompt() was necessary and re-implemented it.
UI fix: Space also closes the config menu on other DOC bbses
> UI fixes and implementation of <a>gain

- load/dmbase.js
- load/dpoast.js
Fixed most addMsg issues
Still needs <E> Enter message (upload) implemented
Reload MsgBase before displaying the prompt to get any new messages
Re-order some events in the scanSub loop so we're not displaying extra prompts
> addMsg fixes

- ddoc2.js
- load/dmbase.js
added msg_base.readNew, docIface.nav.findNew, and heavily modified docIface.nav.skip to move from room to room while scanning for new messages
docIface.nav.skip now marks all messages in the current room as read, as per vDOC
> Added room-to-room scanning

- ddoc2.js
- load/dperroom.js
Room info, while not perfectly implemented (ie it's not yet determining if a person is the one that should be able to modify room info, nor timestamping yet due to my hesitance on settling on a timestamp format) is now correctly saving and reading the room info.  That's good enough to push to dev for me for right now.  Rewriting really helped it out a lot.
> Roominfo rewrite

- load/dexpress.js
- load/dperroom.js
- load/dpoast.js
Enabled room info changed/moderator changed timestamp and cleaned up the extra line that was appended to text blobs in _dpoast.js_.
> Roominfo tidying

- load/dexpress.js
- load/dperroom.js
- load/dpoast.js
- misc/login.js
- misc/logon.js
While the request to do a new mail scan is still there (and needs to not be), the login screens and last logged in users listing has now been removed.  While this is not perfect, it is much quicker and less likely to drive away any DOC users that might come this way.  I'll go ahead and set this ready for a merge now; once I learn how to take out the new message scan bit it's probably in a different file anyway.  Progress has been made.
> Message scan work

- ddoc2.js
Everything isn't working properly yet; this will have to be worked on more in the future.  IE group and sub is not yet being restored properly.  However I did find some other ephemeral bugs that I've taken care of, so I'm gonna go ahead and merge this right now and get it out of the way until I branch out to work on this again.
> Restore sys properties work

- ddoc2.js
- load/dperuser.js
Completed and (I believe) pretty well debugged.
> User profile implementation

- ddoc2.js
- load/dexpress.js
- load/dmail.js
- load/dmbase.js
- load/dperroom.js
- load/dperuser.js
- load/dpoast.js
The wiki text has not yet been updated to reflect the changes that have been found in the functionality of the code.  However, all of the inline code is (at least at 500ft overview status) now documented properly in the headers of the different methods, and a little bit at the sub-object and properties level, as well.  At this point finishing issue #117 should just consist of running again through the source files and copying the notes out of the comment headers into the wiki pages along with additional useful notes on functionality of some of the more involved methods/objects.
> Documentation work

- load/dmbase.js
Made some kludge that'll get around corrupted scan_ptrs for whatever user, should it be necessary.
> Made a quick code fix for overflowing scan_ptr (kludge) #140

- ddoc2.js
- load/dmbase.js
Just need to fix the status line so that it correctly reflects what message has been jumped to by number (as well as how many are remaining, etc).  Reading by number is working correctly.
> Numeric message read

- load/dmbase.js
Wrote ``remap_message_indices()``.  Received some feedback that may have been wrong on that, so it's not implemented anywhere.  For now I'm going to go ahead and merge this; if I find out that more work needs to be done with these features I'll continue later.  Also fixed an issue with a duplicated _util_ object.
> Message scan pointers

- load/dmail.js
- load/dmbase.js
With the added functionality of the _numeric-message-read_ branch being integrated, now is a good time to go ahead and add some more features to master that are ready for beta testing.
> Devel; addition of more good features to master

- ddoc2.js
- load/dmbase.js
- load/dpoast.js
Going to go ahead and submit a merge for this at this point.  There are still some minor bugs to be pulled out of the code that has been added here, but they're suitable for _hotfixing_ and smaller issues than just the message remap support.  Message remapping has been added, and has broken a few things, but the basal feature itself seems to be working at this point, so time to try to bring _devel_ back to current.
> Message remap support

- ddoc2.js
Fixed the error where by jumping to a non-existent room silently fails.
> Closed #184; now shows error if jumping to non-existent room

- README.md
- load/dmail.js
Making sure that devel is up with master now that release 0.1b is out.
> Master->devel for 0.1b release

- load/dmbase.js
I'm not sure what the hell it is, but I swear my git branches have been changing on me at random times lately.  Anyway, this should bring the work that I've been doing that got miscommitted to devel back to hotfix-message-by-number where I want to finish them at.  :|  If this weren't my own repo I'd totally apologize for spamming.
> Got branches mixed up; pulling current work back to current devel status where changes went

- ddoc2.js
- load/dexpress.js
- load/dmail.js
- load/dmbase.js
- load/dperroom.js
- load/dperuser.js
- load/dpoast.js
Finished work on logging and node status changes AFAIK.  Some bugs were introduced, primarily in the _dmbase.js_ and _dmail.js_ files, or else I just didn't notice some more message base issues until now.  Either way I'm going to leave them in and probably just rewrite `scanSub()` at this point because of how fugly and obfuscated it is.  It'd be much better to have a more maintainable version of that routine in place.  It's impossible to look at and understand right now.
> Hotfix finish logging

- ddoc2.js
- load/dmail.js
Worked with post messaging prompt issue, prompting in a few other areas, proper exception throwing/catching, and some other minor code issues, primarily in _dmail.js_.
> Hotfix post mail prompt

- ddoc2.js
- load/dmail.js
Fixes not being able to jump properly out of the _Mail>_ routine.
> Hotfix mail jump fix

- load/dmail.js
_MSG_READ_ usage now properly implemented along with scanning to be able to find the start of unread messages.  _Mail>_ grows vastly more functional.
> Hotfix mail newptr

- load/dmail.js
Added telegram to notify the recipient of _Mail>_ that it has been sent from the dDoc system.
> Closed issue #219

- load/dmbase.js
- load/dpoast.js
Just committing this to devel so that I can be done pussyfooting around with the small stuff and start on the entire rewrite of `scanSub()` while incorporating these changes.
> Hotfix message read last

- ddoc2.js
- load/dperuser.js
Getting this back into the right branches.
> Closed #242; debugging options now setting properly
